# Generated by Django 6.1.1 on 2026-10-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(max_length=50, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=11, verbose_name='R.A.'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_responsavel',
            field=models.CharField(max_length=20, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='descricao',
            field=models.CharField(max_length=75, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('G', 'Grave')], default='L', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
            ],
        ),
    ]
