# Generated by Django 6.1.1 on 2026-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_aluno_cpf_alter_aluno_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='aluno',
            field=models.ManyToManyField(related_name='ocorrencias', to='academico.aluno'),
        ),
    ]
